# Generated by Django 6.0.2 on 2026-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "display_name",
                    models.CharField(max_length=150, verbose_name="Имя автора, которое видят пользователи"),
                ),
                (
                    "subscription_price_rub",
                    models.PositiveIntegerField(default=500, verbose_name="Цена подписки в рублях"),
                ),
                ("stripe_product_id", models.CharField(blank=True, max_length=255)),
                ("stripe_price_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
