# Generated by Django 6.0.2 on 2026-03-11 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="subscription_currency",
        ),
        migrations.AddField(
            model_name="creator",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="creator",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="creator",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="creator",
            name="display_name",
            field=models.CharField(max_length=150, verbose_name="Имя автора, которое видят пользователи"),
        ),
        migrations.AlterField(
            model_name="creator",
            name="subscription_price_rub",
            field=models.PositiveIntegerField(default=500, verbose_name="Цена подписки в рублях"),
        ),
        migrations.AlterField(
            model_name="creator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец профиля автора",
            ),
        ),
    ]
