# Generated by Django 6.0.2 on 2026-03-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0002_remove_creator_subscription_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
