# Generated by Django 6.0.2 on 2026-03-16 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок поста")),
                ("body", models.TextField(verbose_name="Тело поста")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Доступ подписчикам")),
                ("is_published", models.BooleanField(default=False, verbose_name="Публикация поста")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания поста")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата опубликования поста")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="creators.creator",
                        verbose_name="Автор поста",
                    ),
                ),
            ],
        ),
    ]
