# Generated by Django 6.0.2 on 2026-03-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="creators.creator"
            ),
        ),
    ]
